// 词 → 自绘配图文件名。由 tools/build-word-svg.mjs 生成，不要手改。
// 这些词 OpenMoji 没有贴切的图形：要么没有实物（介词、连接词、程度副词），
// 要么是印尼特有的东西（榴莲、天贝、巨港鱼饼）。
export const WORD_SVG = {
  'sebelas': 'sebelas',
  'dua belas': 'dua-belas',
  'tiga belas': 'tiga-belas',
  'empat belas': 'empat-belas',
  'lima belas': 'lima-belas',
  'enam belas': 'enam-belas',
  'tujuh belas': 'tujuh-belas',
  'delapan belas': 'delapan-belas',
  'sembilan belas': 'sembilan-belas',
  'dua puluh': 'dua-puluh',
  'abu-abu': 'abu-abu',
  'merah muda': 'merah-muda',
  'biru muda': 'biru-muda',
  'hijau tua': 'hijau-tua',
  'krem': 'krem',
  'bening': 'bening',
  'warna-warni': 'warna-warni',
  'polos': 'polos',
  'bergaris': 'bergaris',
  'bermotif': 'bermotif',
  'lembut': 'lembut',
  'kontras': 'kontras',
  'senada': 'senada',
  'cocok': 'cocok',
  'pudar': 'pudar',
  'saya': 'saya',
  'aku': 'aku',
  'kamu': 'kamu',
  'anda': 'anda',
  'dia': 'dia',
  'kami': 'kami',
  'kita': 'kita',
  'mereka': 'mereka',
  'kalian': 'kalian',
  'sendiri': 'sendiri',
  'di': 'di',
  'ke': 'ke',
  'dari': 'dari',
  'untuk': 'untuk',
  'dengan': 'dengan',
  'kepada': 'kepada',
  'pada': 'pada',
  'tentang': 'tentang',
  'sampai': 'sampai',
  'tanpa': 'tanpa',
  'dan': 'dan',
  'atau': 'atau',
  'tetapi': 'tetapi',
  'karena': 'karena',
  'jadi': 'jadi',
  'kalau': 'kalau',
  'supaya': 'supaya',
  'walaupun': 'walaupun',
  'lalu': 'lalu',
  'sedangkan': 'sedangkan',
  'sangat': 'sangat',
  'sekali': 'sekali',
  'agak': 'agak',
  'terlalu': 'terlalu',
  'selalu': 'selalu',
  'sering': 'sering',
  'kadang-kadang': 'kadang-kadang',
  'jarang': 'jarang',
  'tidak pernah': 'tidak-pernah',
  'hampir': 'hampir',
  'misalnya': 'misalnya',
  'sebaliknya': 'sebaliknya',
  'selain itu': 'selain-itu',
  'oleh karena itu': 'oleh-karena-itu',
  'meskipun': 'meskipun',
  'sementara itu': 'sementara-itu',
  'bahkan': 'bahkan',
  'singkatnya': 'singkatnya',
  'menurut saya': 'menurut-saya',
  'kesimpulannya': 'kesimpulannya',
  'terlampau': 'terlampau',
  'lumayan': 'lumayan',
  'kelewatan': 'kelewatan',
  'sedikit demi sedikit': 'sedikit-demi-sedikit',
  'semakin': 'semakin',
  'paling sedikit': 'paling-sedikit',
  'nyaris': 'nyaris',
  'berlebihan': 'berlebihan',
  'seadanya': 'seadanya',
  'kira-kira': 'kira-kira',
  'sini': 'sini',
  'situ': 'situ',
  'sana': 'sana',
  'ini': 'ini',
  'itu': 'itu',
  'dekat': 'dekat',
  'jauh': 'jauh',
  'sebelah': 'sebelah',
  'sekitar': 'sekitar',
  'tempat': 'tempat',
  'depan': 'depan',
  'belakang': 'belakang',
  'samping': 'samping',
  'tengah': 'tengah',
  'dalam': 'dalam',
  'luar': 'luar',
  'mungkin': 'mungkin',
  'pasti': 'pasti',
  'belum': 'belum',
  'sudah': 'sudah',
  'menekan': 'menekan',
  'beristirahat': 'beristirahat',
  'membuat': 'membuat',
  'menyimpan': 'menyimpan',
  'hilang': 'hilang',
  'habis': 'habis',
  'muncul': 'muncul',
  'ikut': 'ikut',
  'lewat': 'lewat',
  'butuh': 'butuh',
  'telat': 'telat',
  'mencoba lagi': 'mencoba-lagi',
  'sama-sama': 'sama-sama',
  'tidak apa-apa': 'tidak-apa-apa',
  'boleh': 'boleh',
  'mohon': 'mohon',
  'silakan masuk': 'silakan-masuk',
  'boleh jadi': 'boleh-jadi',
  'sewa bulanan': 'sewa-bulanan',
  'pemilik rumah': 'pemilik-rumah',
  'penyewa': 'penyewa',
  'uang jaminan': 'uang-jaminan',
  'tagihan air': 'tagihan-air',
  'perpanjang sewa': 'perpanjang-sewa',
  'bagasi kabin': 'bagasi-kabin',
  'check-in': 'check-in',
  'pemeriksaan': 'pemeriksaan',
  'kelebihan bagasi': 'kelebihan-bagasi',
  'durian': 'durian',
  'rambutan': 'rambutan',
  'manggis': 'manggis',
  'salak': 'salak',
  'sirsak': 'sirsak',
  'belimbing': 'belimbing',
  'kedondong': 'kedondong',
  'tahu': 'tahu',
  'tempe': 'tempe',
  'singkong': 'singkong',
  'sagu': 'sagu',
  'arem-arem': 'arem-arem',
  'risoles': 'risoles',
  'pempek': 'pempek',
  'cilok': 'cilok',
  'seblak': 'seblak',
  'tempe mendoan': 'tempe-mendoan',
};
